############################################################
# Dockerfile for the reddit query script
############################################################

FROM python:2.7

MAINTAINER Bogdan Stefan

# Copy current directory to mountpoint.
COPY . /reddit

# Define working directory.
WORKDIR /reddit

# Install needed python packages.
RUN pip install -r script_requirements.txt

CMD ['python', 'src/redditQuery.py']